version: '3.7'
services:
  silky.dashboard:
    image: silkyhero/dashboard:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        mode: ${mode:-production}
    ports:
      - 8080:80
