version: "3.7"
services:
 nginx:
  restart: always
  container_name: nginx
  image: nginx:latest
  ports:
   - 80:80
   - 443:443
  volumes:
   - ./conf.d:/etc/nginx/conf.d
   - ./nginx.conf:/etc/nginx/nginx.conf
   - ./cert.d:/etc/nginx/cert.d
  networks:
    - silky_service_net      
      
networks:
  silky_service_net:
    external:
      name: silky_service_net