rpc:
  host: 0.0.0.0
  port: 2200
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
appSettings:
  services:
    - appServiceInterfaceDirectory: C:\workspaces\silky.hero\services\Silky.Organization\src\Silky.OrganizationHost
      appServiceInterfacePattern: Application.Contracts|Domain.Shared|Silky.Hero.Common
  
governance:
  timeoutMillSeconds: 0
registrycenter:
  connectionStrings: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183;127.0.0.1:2184,127.0.0.1:2185,127.0.0.1:2186
  type: Zookeeper
distributedCache:
  redis:
    isEnabled: true
    configuration: 127.0.0.1:6379,defaultDatabase=0
gateway:
  jwtSecret: jv1PZkwjLVCEygM7faLLvEhDGWmFqRUW